### ISSUE TITLE
Preventing Next View Preview on iPad

### ISSUE THREAD

**Issue by pilsen** [exyte/ConcentricOnboarding#17] opened 2023-07-14 15:35 UTC
Hey,

Hope all's good! Noticed a little issue with the app on iPad. There's this preview of the next view showing up on the right side of the screen. Any ideas on how to hide it?

Check out the screenshot: 
![preview-next-view](https://github.com/exyte/ConcentricOnboarding/assets/3148679/d3e2a44b-ec80-4941-a930-5793740f1f21)

Would appreciate your help on this. Thanks a bunch!

Cheers,

**Comment by f3dm76** [comment] 2023-08-18 12:19
Hey @pilsen, thanks for bringing this to our attention! Sorry for the late response. The issue is fixed in version 1.0.4, please check it out. Have a great day!

**Closed as completed by f3dm76** 2023-08-18 12:19 UTC

**Comment by pilsen** [comment] 2023-08-18 12:25
Thank you, I appreciate your response!

#russiaisaterroriststate
